version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
naturalist = true
azurelib = true
bountiful = true
more_slabs_stairs_and_walls = true
sihywtcamd = true
bedspreads = true
overweight_farming = true
therm = true
vs_eureka = true
valkyrienskies = true
rocks = true
diagonalwindows = true
snowrealmagic = true
copper_golem = true
diagonalfences = true
livingthings = true
carpeted = true
visualoverhaul = true
minecraft = true
animal_feeding_trough = true
