
#RubidiumToolkit
[Settings]

	[Settings."Dynamic Lights"]
		"Dynamic TileEntity Lighting" = true
		"Only Update On Position Change" = true
		"Quality Mode (OFF, SLOW, FAST, REALTIME)" = "REALTIME"
		"Dynamic Entity Lighting" = true

	[Settings.Misc]
		"Render Fog" = true

	[Settings.zoom]
		"zoom Transition Mode (OFF, LINEAR, SMOOTH)" = "SMOOTH"
		"zoom Transition Mode (TOGGLE, HOLD, PERSISTENT)" = "HOLD"
		"Cinematic Camera Mode (OFF, VANILLA, MULTIPLIED)" = "VANILLA"
		"Lower zoom Sensitivity" = true
		"zoom Scrolling Enabled" = false
		"zoom Overlay?" = false

	[Settings."Entity Distance"]
		"Enable Max Distance Checks" = false
		"(Entity) Max Vertical Render Distance [Raw, Default 32]" = 32
		"(Entity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(TileEntity) Max Horizontal Render Distance [Squared, Default 64^2]" = 4096
		"(TileEntity) Max Vertical Render Distance [Raw, Default 32]" = 32

