
[general]
	#Should draw overlay over the fake slots
	fake_slot_overlay = true
	#Should hide the offhand slot? Ignored if disableOffhand in the common config is true
	hide_offhand = false
	#Color of the fake slot overlay
	#Range: > 0
	fake_slot_overlay_color = 13027014

